name: ashtar_super_admin
version: 1.0.0+1
description: A new Flutter project.
publish_to: none

dependencies:
  build_runner: 2.3.3
  cupertino_icons: ^1.0.2
  dartz: 0.10.1
  dio: 5.0.0
  firebase_core: 2.6.1
  firebase_messaging: 14.2.4
  firebase_storage: 11.0.13
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.4.0
  get: 4.6.5
  google_fonts: 4.0.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  hive_generator: 2.0.0
  image_picker: 0.8.6+2
  intl: 0.18.0
  pluto_grid: 6.0.2
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1
  retrofit_generator: 5.0.0
  

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.19.2 <3.0.0"

flutter:
  uses-material-design: true
  